global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # User Service
  - job_name: 'user-service'
    metrics_path: '/api/actuator/prometheus'
    static_configs:
      - targets: ['user-service:8080']
    scrape_interval: 30s
    scrape_timeout: 10s

  # Kafka
  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:9101']

  # Redis
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']

  # PostgreSQL
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']